"""add categories

Revision ID: 67b68e589493
Revises: da61edc5cc43
Create Date: 2026-08-07 17:16:46.476907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b68e589493'
down_revision: Union[str, Sequence[str], None] = 'da61edc5cc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('master_services', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_master_services_category_id'), 'master_services', ['category_id'], unique=False)
    op.create_foreign_key('fk_master_services_category_id_categories', 'master_services', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_master_services_category_id_categories', 'master_services', type_='foreignkey')
    op.drop_index(op.f('ix_master_services_category_id'), table_name='master_services')
    op.drop_column('master_services', 'category_id')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
