"""link users to masters

Revision ID: 8a0d5071ba67
Revises: d1e04b25b0c6
Create Date: 2026-08-07 10:19:51.251182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0d5071ba67'
down_revision: Union[str, Sequence[str], None] = 'd1e04b25b0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_masters_user_id', 'masters', ['user_id'])
    op.create_foreign_key('fk_masters_user_id_users', 'masters', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_masters_user_id_users', 'masters', type_='foreignkey')
    op.drop_constraint('uq_masters_user_id', 'masters', type_='unique')
    op.drop_column('masters', 'user_id')
    # ### end Alembic commands ###
