"""link bookings to users

Revision ID: da61edc5cc43
Revises: 8a0d5071ba67
Create Date: 2026-08-07 13:13:02.729376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da61edc5cc43'
down_revision: Union[str, Sequence[str], None] = '8a0d5071ba67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_foreign_key('fk_bookings_client_id_users', 'bookings', 'users', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookings_client_id_users', 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_column('bookings', 'client_id')
    # ### end Alembic commands ###
